<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ascube.Mwm.Core\Ascube.Mwm.Core.csproj" />
    <ProjectReference Include="..\Ascube.Mwm.Store\Ascube.Mwm.Store.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
  </ItemGroup>

</Project>
